// [snowpack] add styles to the page (skip if no document exists)
if (typeof document !== 'undefined') {
  const code = "/*!\n  Theme: GitHub Dark Dimmed\n  Description: Dark dimmed theme as seen on github.com\n  Author: github.com\n  Maintainer: @Hirse\n  Updated: 2021-05-15\n\n  Colors taken from GitHub's CSS\n*/\n\n.hljs {\n  color: #adbac7;\n  background: #22272e;\n}\n\n.hljs-doctag,\n.hljs-keyword,\n.hljs-meta .hljs-keyword,\n.hljs-template-tag,\n.hljs-template-variable,\n.hljs-type,\n.hljs-variable.language_ {\n  /* prettylights-syntax-keyword */\n  color: #f47067;\n}\n\n.hljs-title,\n.hljs-title.class_,\n.hljs-title.class_.inherited__,\n.hljs-title.function_ {\n  /* prettylights-syntax-entity */\n  color: #dcbdfb;\n}\n\n.hljs-attr,\n.hljs-attribute,\n.hljs-literal,\n.hljs-meta,\n.hljs-number,\n.hljs-operator,\n.hljs-variable,\n.hljs-selector-attr,\n.hljs-selector-class,\n.hljs-selector-id {\n  /* prettylights-syntax-constant */\n  color: #6cb6ff;\n}\n\n.hljs-regexp,\n.hljs-string,\n.hljs-meta .hljs-string {\n  /* prettylights-syntax-string */\n  color: #96d0ff;\n}\n\n.hljs-built_in,\n.hljs-symbol {\n  /* prettylights-syntax-variable */\n  color: #f69d50;\n}\n\n.hljs-comment,\n.hljs-code,\n.hljs-formula {\n  /* prettylights-syntax-comment */\n  color: #768390;\n}\n\n.hljs-name,\n.hljs-quote,\n.hljs-selector-tag,\n.hljs-selector-pseudo {\n  /* prettylights-syntax-entity-tag */\n  color: #8ddb8c;\n}\n\n.hljs-subst {\n  /* prettylights-syntax-storage-modifier-import */\n  color: #adbac7;\n}\n\n.hljs-section {\n  /* prettylights-syntax-markup-heading */\n  color: #316dca;\n  font-weight: bold;\n}\n\n.hljs-bullet {\n  /* prettylights-syntax-markup-list */\n  color: #eac55f;\n}\n\n.hljs-emphasis {\n  /* prettylights-syntax-markup-italic */\n  color: #adbac7;\n  font-style: italic;\n}\n\n.hljs-strong {\n  /* prettylights-syntax-markup-bold */\n  color: #adbac7;\n  font-weight: bold;\n}\n\n.hljs-addition {\n  /* prettylights-syntax-markup-inserted */\n  color: #b4f1b4;\n  background-color: #1b4721;\n}\n\n.hljs-deletion {\n  /* prettylights-syntax-markup-deleted */\n  color: #ffd8d3;\n  background-color: #78191b;\n}\n\n.hljs-char.escape_,\n.hljs-link,\n.hljs-params,\n.hljs-property,\n.hljs-punctuation,\n.hljs-tag {\n  /* purposely ignored */\n}\n";

  const styleEl = document.createElement("style");
  const codeEl = document.createTextNode(code);
  styleEl.type = 'text/css';
  styleEl.appendChild(codeEl);
  document.head.appendChild(styleEl);
}